### ISSUE TITLE
请问precision、recall、f1分别是多少，谢谢

### ISSUE THREAD

**Issue by lijiaoyang** [mangonihao/EntityRelationExtraction#2]

**Comment by mangonihao** [comment]
我记得命名实体识别任务的召回率好像可以达到0.9。关系抽取的忘记了，不过也挺高，BiLSTM+CRF做命名实体识别，Bert做关系抽取都很常见

**Comment by lijiaoyang** [comment]
谢谢回复，您提供的数据集百度网盘下载不了，提示密码错误

发送自 Windows 10 版邮件应用

发件人: mangoicecream
发送时间: 2021年6月8日 10:37
收件人: mangonihao/EntityRelationExtraction
抄送: lijiaoyang; Author
主题: Re: [mangonihao/EntityRelationExtraction] 请问precision、recall、f1分别是多少，谢谢 (#2)

我记得命名实体识别任务的召回率好像可以达到0.9。关系抽取的忘记了，不过也挺高，BiLSTM+CRF做命名实体识别，Bert做关系抽取都很常见

**Comment by mangonihao** [comment]
> 谢谢回复，您提供的数据集百度网盘下载不了，提示密码错误 发送自 Windows 10 版邮件应用 发件人: mangoicecream 发送时间: 2021年6月8日 10:37 收件人: mangonihao/EntityRelationExtraction 抄送: lijiaoyang; Author 主题: Re: [mangonihao/EntityRelationExtraction] 请问precision、recall、f1分别是多少，谢谢 (#2) 我记得命名实体识别任务的召回率好像可以达到0.9。关系抽取的忘记了，不过也挺高，BiLSTM+CRF做命名实体识别，Bert做关系抽取都很常见 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

应该是你密码输入错误了。密码最后一个是数字0，而不是字母
