### ISSUE TITLE
没有vocab.txt文件

### ISSUE THREAD

**Issue by shenjing023** [mangonihao/EntityRelationExtraction#3]
项目中没有vocab.txt这个文件，提供的数据集中也没有
```
# config_ner.py

self.vocab_file = '../data/vocab.txt'
```

**Comment by mangonihao** [comment]
> 项目中没有vocab.txt这个文件，提供的数据集中也没有
> 
> ```
> # config_ner.py
> 
> self.vocab_file = '../data/vocab.txt'
> ```

这个vocab.txt文件在hugging face的预训练模型处下载，你下载bert预训练模型的地方有这个文件，下载地址：https://huggingface.co/bert-base-chinese/tree/main
