### ISSUE TITLE
data

### ISSUE THREAD

**Issue by beitata** [mangonihao/EntityRelationExtraction#4]
老师，您好， vec.txt在哪呀，

**Comment by mangonihao** [comment]
> 老师，您好， vec.txt

> 老师，您好， vec.txt在哪呀，

**Comment by mangonihao** [comment]
> 老师，您好， vec.txt在哪呀，
使用预训练模型时，不需要这个文件；使用BIGRU也是从头开始训练的，不需要加载预训练词向量

**Comment by beitata** [comment]
> > 老师，您好， vec.txt在哪呀，
> > 使用预训练模型时，不需要这个文件；使用BIGRU也是从头开始训练的，不需要加载预训练词向量

'../data/train_data_small.json',
    '../data/dev_small.json',
    '../data/predict.json'
这几个数据都是对应的数据集里面的train，dev 和test吗
老师，实体识别和关系识别都是用的一个数据集吗
