### ISSUE TITLE
询问

### ISSUE THREAD

**Issue by 974413659** [mangonihao/EntityRelationExtraction#5]
你好，我想问一下，代码中的neptune 是与服务器相关的么？因为这个包一直无法下载，我在想有没有其他包可以代替这个包的作用呢？

**Comment by mangonihao** [comment]
> 你好，我想问一下，代码中的neptune 是与服务器相关的么？因为这个包一直无法下载，我在想有没有其他包可以代替这个包的作用呢？
与服务器无关，是一个类似TensflowBoard的可视化包，你可以搜一下怎么安装或者注释掉这部分。

**Comment by 974413659** [comment]
麻烦你了，谢谢你的回复。问题已解决。



在 2022-04-03 12:33:44，"mangoicecream" ***@***.***> 写道：

你好，我想问一下，代码中的neptune 是与服务器相关的么？因为这个包一直无法下载，我在想有没有其他包可以代替这个包的作用呢？
与服务器无关，是一个类似TensflowBoard的可视化包，你可以搜一下怎么安装或者注释掉这部分。
