### ISSUE TITLE
关于数据集

### ISSUE THREAD

**Issue by kol66** [mangonihao/EntityRelationExtraction#6]
../data/train_data_small.json',
'../data/dev_small.json',
'../data/predict.json'
请问这几个数据是对应的百度数据集里面的train，dev 和test吗

**Comment by mangonihao** [comment]
> ../data/train_data_small.json', '../data/dev_small.json', '../data/predict.json' 请问这几个数据是对应的百度数据集里面的train，dev 和test吗

train， test和预测的结果，没有单独设置dev
