### ISSUE TITLE
关于vocab

### ISSUE THREAD

**Issue by kol66** [mangonihao/EntityRelationExtraction#7]
请问config_ner.py这个路径的vocab.txt是预训练模型bert-base-chinese的吗？还是自己构造的？
![image](https://user-images.githubusercontent.com/97020095/169653768-13595cac-86bd-4d81-bec8-698666ef1354.png)

**Comment by mangonihao** [comment]
> 请问config_ner.py这个路径的vocab.txt是预训练模型bert-base-chinese的吗？还是自己构造的？ ![image](https://user-images.githubusercontent.com/97020095/169653768-13595cac-86bd-4d81-bec8-698666ef1354.png)

你看一下下载的data文件夹有vocab.txt没？如果没有，应该就是BERT的vocab.txt

**Comment by kol66** [comment]
> 

好的，感谢
